const express = require("express");
const PDFDocument = require("pdfkit");
const { protect, authorize } = require("../middleware/authMiddleware");
const Project = require("../models/Project");
const Task = require("../models/Task");

const router = express.Router();

router.get("/export", protect, authorize("admin", "project_manager"), async (req, res) => {
  try {
    const { projectId, startDate, endDate } = req.query;

    // Filter projects
    const projQuery = {};
    if (projectId && projectId !== "All") {
      projQuery._id = projectId;
    }
    if (req.user.role !== "admin") {
      projQuery.$or = [{ owner: req.user._id }, { "members.user": req.user._id }];
    }
    const projects = await Project.find(projQuery)
      .populate("owner", "name email")
      .populate("members.user", "name email");

    // Filter tasks
    const taskQuery = {};
    if (projectId && projectId !== "All") {
      taskQuery.project = projectId;
    }
    if (req.user.role !== "admin") {
      const allowedProjectIds = projects.map(p => p._id);
      taskQuery.$or = [
        { assignedTo: req.user._id },
        { createdBy: req.user._id },
        { project: { $in: allowedProjectIds } }
      ];
    }
    const tasks = await Task.find(taskQuery)
      .populate("assignedTo", "name email")
      .populate("project", "name");

    // Filter by dates if provided
    let filteredProjects = projects;
    let filteredTasks = tasks;

    if (startDate) {
      const sDate = new Date(startDate);
      filteredProjects = filteredProjects.filter(p => new Date(p.createdAt || p.startDate) >= sDate);
      filteredTasks = filteredTasks.filter(t => new Date(t.createdAt) >= sDate);
    }
    if (endDate) {
      const eDate = new Date(endDate);
      eDate.setHours(23, 59, 59, 999);
      filteredProjects = filteredProjects.filter(p => new Date(p.createdAt || p.startDate) <= eDate);
      filteredTasks = filteredTasks.filter(t => new Date(t.createdAt) <= eDate);
    }

    // Generate PDF using pdfkit
    const doc = new PDFDocument({ margin: 50, size: "A4", bufferPages: true });

    // Set Response Headers
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", 'attachment; filename="workspace_report.pdf"');

    doc.pipe(res);

    // Header branding
    doc.fillColor("#1e293b").rect(0, 0, 595.28, 90).fill(); // dark blue banner
    doc.fillColor("#ffffff").fontSize(20).font("Helvetica-Bold").text("TaskFlow Pro", 50, 25);
    doc.fontSize(11).font("Helvetica").text("Workspace Performance & Progress Report", 50, 50);

    // Generation Info
    doc.fillColor("#1e293b").fontSize(10).font("Helvetica-Bold").text("Report Metadata", 50, 110);
    doc.font("Helvetica").text(`Generated on: ${new Date().toLocaleString()}`, 50, 130);
    doc.text(`Generated by: ${req.user.name} (${req.user.email})`, 50, 145);
    
    let filterText = "Filters applied: ";
    if (projectId && projectId !== "All") {
      const selectedProj = projects.find(p => String(p._id) === String(projectId));
      filterText += `Project: ${selectedProj ? selectedProj.name : projectId}; `;
    } else {
      filterText += "Project: All; ";
    }
    if (startDate) filterText += `Start Date: ${startDate}; `;
    if (endDate) filterText += `End Date: ${endDate}; `;
    doc.text(filterText, 50, 160);

    // Summary statistics
    const compTasks = filteredTasks.filter(t => t.status === "Completed").length;
    const rate = filteredTasks.length > 0 ? Math.round((compTasks / filteredTasks.length) * 100) : 0;

    doc.rect(50, 185, 495, 55).strokeColor("#cbd5e1").lineWidth(1).stroke();
    doc.fontSize(11).font("Helvetica-Bold").text("Summary Metrics", 60, 195);
    doc.fontSize(10).font("Helvetica");
    doc.text(`Total Projects: ${filteredProjects.length}`, 60, 215);
    doc.text(`Tasks Completed: ${compTasks} / ${filteredTasks.length} (${rate}% Completion)`, 200, 215);
    const overdue = filteredTasks.filter(t => t.dueDate && new Date(t.dueDate) < new Date() && t.status !== "Completed").length;
    doc.text(`Overdue Tasks: ${overdue}`, 410, 215);

    // Projects Section
    doc.fontSize(14).font("Helvetica-Bold").text("Projects Overview", 50, 260);
    doc.moveTo(50, 280).lineTo(545, 280).strokeColor("#94a3b8").stroke();

    let y = 295;
    if (filteredProjects.length === 0) {
      doc.fontSize(10).font("Helvetica-Oblique").text("No projects found matching the criteria.", 50, y);
      y += 25;
    } else {
      filteredProjects.forEach((proj, idx) => {
        if (y > 700) {
          doc.addPage();
          y = 50;
        }
        doc.fontSize(11).font("Helvetica-Bold").text(`${idx + 1}. ${proj.name}`, 50, y);
        doc.fontSize(9).font("Helvetica").text(`Status: ${proj.status}  |  Progress: ${proj.progress || 0}%  |  Priority: ${proj.priority}`, 50, y + 15);
        doc.text(`Owner: ${proj.owner?.name || "N/A"}  |  Members: ${proj.members?.length || 0}`, 50, y + 27);
        y += 50;
      });
    }

    // Tasks Section
    y += 20;
    if (y > 650) {
      doc.addPage();
      y = 50;
    }

    doc.fontSize(14).font("Helvetica-Bold").text("Tasks Detail", 50, y);
    doc.moveTo(50, y + 20).lineTo(545, y + 20).strokeColor("#94a3b8").stroke();
    y += 35;

    if (filteredTasks.length === 0) {
      doc.fontSize(10).font("Helvetica-Oblique").text("No tasks found matching the criteria.", 50, y);
    } else {
      filteredTasks.forEach((task, idx) => {
        if (y > 700) {
          doc.addPage();
          y = 50;
        }
        doc.fontSize(10).font("Helvetica-Bold").text(`${idx + 1}. ${task.title}`, 50, y);
        const pName = task.project?.name || "General Task";
        doc.fontSize(9).font("Helvetica").text(`Project: ${pName}  |  Assignee: ${task.assignedTo?.name || "Unassigned"}`, 50, y + 14);
        const dueText = task.dueDate ? new Date(task.dueDate).toLocaleDateString() : "No due date";
        doc.text(`Status: ${task.status}  |  Priority: ${task.priority}  |  Due Date: ${dueText}`, 50, y + 26);
        y += 48;
      });
    }

    // Footer with Page Numbers
    const pages = doc.bufferedPageRange();
    for (let i = 0; i < pages.count; i++) {
      doc.switchToPage(i);
      doc.fontSize(8).fillColor("#94a3b8").text(`Page ${i + 1} of ${pages.count}`, 50, 800, { align: "center", width: 495 });
    }

    doc.end();

  } catch (error) {
    console.error("Export PDF Error:", error);
    res.status(500).json({ message: "Failed to generate report PDF." });
  }
});

module.exports = router;
